welcome_message_file:
  - /etc/motd
  - /etc/issue
  - /etc/issue.net

syslog_data:
    # - { regexp_string: "minlen", rule: "minlen = 8"}
  - {regexp_string: 'authpriv.*/var/log/secure' , rule: 'authpriv.* /var/log/secure'}
  - {regexp_string: 'cron.*/var/log/cron' , rule: 'cron.* /var/log/cron'}
  - {regexp_string: 'kern.*/var/adm/messages' , rule: '*.err;kern.debug;daemon.notice; /var/adm/messages'}

limit_list:
  - "* soft nofile 655350"
  - "* hard nofile 655350"
  - "* soft nproc 65535"
  - "* hard nproc 65535"

pam_login_strategy_file:
  - /etc/pam.d/password-auth
  - /etc/pam.d/system-auth

close_service_list:
  #用于分发系统配置文件的客户端 - 服务器目录服务协议。 NIS服务器是允许分发配置文件的程序集合。
  - 'ypserv'
  - 'snmpd'
  #dhcp server
  - 'named'
  - 'rsh.socket'
  - 'rexec.socket'
  - 'rlogin.socket'
  - 'telnet.socket'
  - "postfix"
  - "sendmail"
  - "autofs"
  #daytime是一种网络服务，它以服务器的当前日期和时间作为响应。该服务旨在用于调试和测试目的
  - "daytime-dgram"

no_login_user:
  - 'tcpdump'
  - 'postfix'
  - 'dbus'
  - 'lp'
  - 'vnstat'
  - 'chrony'
  - 'nfsnobody'
  - 'docker'
  - 'nginx'
  - 'apache'
  - 'mysql'
  - 'redis'
  - 'docker'
  - 'jenkins'
  - 'gitlab'
  - 'sonarqube'
  - 'nexus'
  - 'zookeeper'
  - 'kafka'
  - 'consul'
  - 'etcd'
  - 'prometheus'
  - 'grafana'
  - 'openvpn'
  - 'tomcat'
  - 'jetty'
  - 'glassfish'
  - 'wildfly'
  - 'elasticsearch'
  - 'kibana'
  - 'logstash'
  - 'fluentd'
  - 'mongodb'
  - 'mariadb'
  - 'postgresql'
  - 'cassandra'
  - 'couchbase'
  - 'presto'
  - 'clickhouse'
  - 'memsql'
  - 'aerospike'
  - 'neo4j'
  - 'influxdb'
  - 'splunk'
  - 'graylog'
  - 'falcon'
  - 'ceph'
  - 'glusterfs'
  - 'abrt'
  - 'ntp'

file_permission_list:
  - {path: "/etc/cron.monthly" ,  owner: "root" , group: "root" , mode: "0700" }
  - {path: "/etc/cron.daily" ,  owner: "root" , group: "root" , mode: "0700" }
  - { path: "/etc/passwd" , owner: "root" , group: "root" , mode: "0644" }
  - { path: "/etc/passwd-" , owner: "root" , group: "root" , mode: "0644" }
  - { path: "/etc/group" , owner: "root" , group: "root" , mode: "0644" }
  - { path: "/etc/group-" , owner: "root" , group: "root" , mode: "0644" }
  - { path: "/etc/shadow" , owner: "root" , group: "root" , mode: "0000" }
  - { path: "/etc/shadow-" , owner: "root" , group: "root" , mode: "0000" }
  - { path: "/etc/gshadow" , owner: "root" , group: "root" , mode: "0000" }
  - { path: "/boot/grub2/grub.cfg" , owner: "root" , group: "root" , mode: "0600" }