- name: 禁止快捷键重启
  ansible.builtin.file:
    path: /usr/lib/systemd/system/ctrl-alt-del.target
    state: absent
  tags: safe

- name: 关闭非必要服务
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped 
    enabled: false
  with_items: "{{ close_service_list }}"
  tags: 
  - safe
  - disible-service