- name: 修改关键文件权限
  ansible.builtin.file: 
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:  "{{ file_permission_list }}"
  tags: file-permission