- name: Install ntpdate
  ansible.builtin.package:
    name:
      - ntpdate
      - util-linux #提供hwclock
    state: present

- name: Install cron
  ansible.builtin.package:
    pkg: { item.pkg }
  when: (ansible_facts['distribution'] == "Ubuntu")
  loop: 
  - { pkg: "cron" ,  distros: ['CentOS'] }
  - { pkg: "cronie" ,distros: ['Ubuntu'] }
  tags:
  - ntp
  

- name: set ntp
  ansible.builtin.cron:
    name: "time sync for ntp"
    job: "/usr/sbin/ntpdate ntp.aliyun.com && /sbin/hwclock -w"
    hour: "*"
    state: present
  tags: ntp
