- name: 更新root密码
  ansible.builtin.set_fact:
      new_root_password: "{{ lookup('password', '/dev/null'   , chars = ['ascii_letters', 'digits','!@$%^&*()_+-=,./?;}{}()[]'] ) }}"
      # new_root_password: 'www.160.com'
- name: 更新root密码
  ansible.builtin.user:
      name: root
      password: "{{ new_root_password | password_hash('sha512') }}"
      update_password: always 
- name: 更新root密码
  ansible.builtin.debug:
      msg:   "{{  new_root_password  }}"
        