- name: 生成新 root 密码
  ansible.builtin.set_fact:
    new_root_password: "{{ lookup('password', '/dev/null', chars=['ascii_letters', 'digits', '!@$%^&*()_+-=,./?;}{}()[]']) }}"
  when: root_change_password | default(false) | bool
  tags: 
  - password
  - safa

- name: 更新 root 密码
  ansible.builtin.user:
    name: root
    password: "{{ new_root_password | password_hash('sha512') }}"
    update_password: always
  register: password_update_result
  when: root_change_password | default(false) | bool
  tags: 
  - password
  - safa

- name: 设置 root 密码修改标识
  ansible.builtin.set_fact:
    root_password_changed: "{{ password_update_result is changed }}"
  when: root_change_password | default(false) | bool
  tags: 
  - password
  - safa
  
- name: 显示新 root 密码
  ansible.builtin.debug:
    msg: "新 root 密码: {{ new_root_password }}（已修改: {{ root_password_changed | default(false) }})"
  when: root_change_password | default(false) | bool
  tags: 
  - password
  - safa