#TODO 
# 1. install openresty soure
# 2. install openresty 
# 3. configure openresty  default 
# 4. logrote to openresty log
- name: test
  debug:
    msg: 111
  tags: openresty

- name: test22
  debug:
    msg: 222
  tags: openresty2

